# Generated by Django 2.2.5 on 2019-11-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
