# Generated by Django 2.2.5 on 2019-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='<h1> default </h1>'),
            preserve_default=False,
        ),
    ]
